version: '3'
services:
  prometheus:
    image: ghcr.io/pausegarra/prometheus:${VERSION}
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: ghcr.io/pausegarra/grafana:${VERSION}
    container_name: grafana
    ports:
      - "3030:3000"
    restart: always
    depends_on:
      - prometheus
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    volumes:
      - grafana-data:/var/lib/grafana

  blackbox-exporter:
    image: ghcr.io/pausegarra/blackbox-exporter:${VERSION}
    container_name: blackbox-exporter
    restart: always
    ports:
      - "9115:9115"

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx_exporter
    command:
      - -nginx.scrape-uri=http://host.docker.internal:3029/stub_status
    ports:
      - "9113:9113"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.53.0
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "9114:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus-data:
  grafana-data: