name: Deploy Application ðŸ‹

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-grafana:
    name: ðŸ‹ Build and Push Grafana Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: ðŸ”½ Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ› ï¸ Build Docker Image
        run: |
          docker build -t ghcr.io/pausegarra/grafana:${{ github.ref_name }} -f Dockerfile.grafana .

      - name: ðŸ› ï¸ Push Docker Image to Registry
        run: |
          docker push ghcr.io/pausegarra/grafana:${{ github.ref_name }}

  build-prometheus:
    name: ðŸ‹ Build and Push Prometheus Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: ðŸ”½ Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ› ï¸ Build Docker Image
        run: |
          docker build -t ghcr.io/pausegarra/prometheus:${{ github.ref_name }} -f Dockerfile.prometheus .

      - name: ðŸ› ï¸ Push Docker Image to Registry
        run: |
          docker push ghcr.io/pausegarra/prometheus:${{ github.ref_name }}

  build-blackbox:
    name: ðŸ‹ Build and Push Blackbox Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: ðŸ”½ Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ› ï¸ Build Docker Image
        run: |
          docker build -t ghcr.io/pausegarra/blackbox-exporter:${{ github.ref_name }} -f Dockerfile.blackbox .

      - name: ðŸ› ï¸ Push Docker Image to Registry
        run: |
          docker push ghcr.io/pausegarra/blackbox-exporter:${{ github.ref_name }}

  deploy:
    name: ðŸš€ Deploy Application
    runs-on: ubuntu-latest
    needs: [build-grafana, build-prometheus, build-blackbox]

    steps:
      - name: ðŸ”½ Checkout
        uses: actions/checkout@v4

      - name: ðŸš€ Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          cat ./compose.yaml | ssh -o StrictHostKeyChecking=no -i id_rsa -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "docker pull ghcr.io/pausegarra/grafana:${{ github.ref_name }} && \
             docker pull ghcr.io/pausegarra/blackbox-exporter:${{ github.ref_name }} && \
             docker pull ghcr.io/pausegarra/prometheus:${{ github.ref_name }} && \
              export VERSION=${{ github.ref_name }} && \
              export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} && \
              export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} && \
              export KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} && \
              export KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }} && \
            docker compose -f - up -d --force-recreate"
          rm id_rsa